name: Update blog

on: [push, repository_dispatch]

jobs:
  update:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install --prod --pure-lockfile
      
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: add bread-compressor-cli -D
      
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: run deploy

        env:
          GHOST_API_URL: "https://blog.conor-burns.com"
          GHOST_CONTENT_API_KEY: ${{ secrets.ghost_content_api_key }}
          GATSBY_ENV: "prod"

      - name: Deploy
        run: docker-compose run deploy
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key }}
