name: Update blog

on: [push, repository_dispatch]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - name: Build
        uses: comchangs/action-yarn@master
        with:
          args: yarn install --prod --pure-lockfile; yarn add bread-compressor-cli -D; yarn run deploy
        env:
          GHOST_API_URL: "https://blog.conor-burns.com"
          GHOST_CONTENT_API_KEY: ${{ secrets.ghost_content_api_key }}
          GATSBY_ENV: "prod"

      - name: Deploy
        run: docker-compose run deploy
        env:
          DEPLOY_KEY: ${{ secrets.deploy_key }}
